### ISSUE TITLE
StopIteration: too many indices for array

### ISSUE THREAD

**Issue by Lakshya-Kejriwal** [experiencor/keras-yolo3#106]
Hi,

I am training on a custom data set. I generated all the xml file but when I start training I am getting the following error.

```
Epoch 1/103
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 257, in _main_
    max_queue_size   = 8
  File "/home/vulcan/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/vulcan/.local/lib/python2.7/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/home/vulcan/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "/home/vulcan/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
StopIteration: too many indices for array
```

Can anyone tell where I am going wrong?

**Comment by Srutarshi** [comment]
Has this issue been solved ? I am getting the same error as well.
