### ISSUE TITLE
Hi .. python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg

### ISSUE THREAD

**Issue by SteveIb** [experiencor/keras-yolo3#113]
Hi I have the following error when runnung the command 
python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg

Using Theano backend.
loading weights of convolution #0
loading weights of convolution #1
loading weights of convolution #2
loading weights of convolution #3
no convolution #4
loading weights of convolution #5
loading weights of convolution #6
loading weights of convolution #7
no convolution #8
loading weights of convolution #9
loading weights of convolution #10
no convolution #11
loading weights of convolution #12
loading weights of convolution #13
loading weights of convolution #14
no convolution #15
loading weights of convolution #16
loading weights of convolution #17
no convolution #18
loading weights of convolution #19
loading weights of convolution #20
no convolution #21
loading weights of convolution #22
loading weights of convolution #23
no convolution #24
loading weights of convolution #25
loading weights of convolution #26
no convolution #27
loading weights of convolution #28
loading weights of convolution #29
no convolution #30
loading weights of convolution #31
loading weights of convolution #32
no convolution #33
loading weights of convolution #34
loading weights of convolution #35
no convolution #36
loading weights of convolution #37
loading weights of convolution #38
loading weights of convolution #39
no convolution #40
loading weights of convolution #41
loading weights of convolution #42
no convolution #43
loading weights of convolution #44
loading weights of convolution #45
no convolution #46
loading weights of convolution #47
loading weights of convolution #48
no convolution #49
loading weights of convolution #50
loading weights of convolution #51
no convolution #52
loading weights of convolution #53
loading weights of convolution #54
no convolution #55
loading weights of convolution #56
loading weights of convolution #57
no convolution #58
loading weights of convolution #59
loading weights of convolution #60
no convolution #61
loading weights of convolution #62
loading weights of convolution #63
loading weights of convolution #64
no convolution #65
loading weights of convolution #66
loading weights of convolution #67
no convolution #68
loading weights of convolution #69
loading weights of convolution #70
no convolution #71
loading weights of convolution #72
loading weights of convolution #73
no convolution #74
loading weights of convolution #75
loading weights of convolution #76
loading weights of convolution #77
loading weights of convolution #78
loading weights of convolution #79
loading weights of convolution #80
loading weights of convolution #81
no convolution #82
no convolution #83
loading weights of convolution #84
no convolution #85
no convolution #86
loading weights of convolution #87
loading weights of convolution #88
loading weights of convolution #89
loading weights of convolution #90
loading weights of convolution #91
loading weights of convolution #92
loading weights of convolution #93
no convolution #94
no convolution #95
loading weights of convolution #96
no convolution #97
no convolution #98
loading weights of convolution #99
loading weights of convolution #100
loading weights of convolution #101
loading weights of convolution #102
loading weights of convolution #103
loading weights of convolution #104
loading weights of convolution #105
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 434, in <module>
    _main_(args)
  File "yolo3_one_file_to_detect_them_all.py", line 409, in _main_
    image_h, image_w, _ = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by PhilippMarquardt** [comment]
I had the same problem. In my specific problem some of the filepaths in the xml files were missing the .jpg ending. I changed one method in the generator.py file: 
 ```
def load_image(self, i):
        image = cv2.imread(self.instances[i]['filename'])
        if image is None:
            image = cv2.imread(self.instances[i]['filename'] + '.jpg')
        return image
```

It helped me.

**Comment by PhilippMarquardt** [comment]
Are you sure that your filepath to the image is correct? The error is caused when you give the `cv.imread()` function a wrong filepath.

**Comment by zhangzhiyong18** [comment]
This indicates that the path of the image is not set correctly

**Comment by 459below** [comment]
> Hi I have the following error when runnung the command
> python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg
> 
> Using Theano backend.
> loading weights of convolution #0
> loading weights of convolution #1
> loading weights of convolution #2
> loading weights of convolution #3
> no convolution #4
> loading weights of convolution #5
> loading weights of convolution #6
> loading weights of convolution #7
> no convolution #8
> loading weights of convolution #9
> loading weights of convolution #10
> no convolution #11
> loading weights of convolution #12
> loading weights of convolution #13
> loading weights of convolution #14
> no convolution #15
> loading weights of convolution #16
> loading weights of convolution #17
> no convolution #18
> loading weights of convolution #19
> loading weights of convolution #20
> no convolution #21
> loading weights of convolution #22
> loading weights of convolution #23
> no convolution #24
> loading weights of convolution #25
> loading weights of convolution #26
> no convolution #27
> loading weights of convolution #28
> loading weights of convolution #29
> no convolution #30
> loading weights of convolution #31
> loading weights of convolution #32
> no convolution #33
> loading weights of convolution #34
> loading weights of convolution #35
> no convolution #36
> loading weights of convolution #37
> loading weights of convolution #38
> loading weights of convolution #39
> no convolution #40
> loading weights of convolution #41
> loading weights of convolution #42
> no convolution #43
> loading weights of convolution #44
> loading weights of convolution #45
> no convolution #46
> loading weights of convolution #47
> loading weights of convolution #48
> no convolution #49
> loading weights of convolution #50
> loading weights of convolution #51
> no convolution #52
> loading weights of convolution #53
> loading weights of convolution #54
> no convolution #55
> loading weights of convolution #56
> loading weights of convolution #57
> no convolution #58
> loading weights of convolution #59
> loading weights of convolution #60
> no convolution #61
> loading weights of convolution #62
> loading weights of convolution #63
> loading weights of convolution #64
> no convolution #65
> loading weights of convolution #66
> loading weights of convolution #67
> no convolution #68
> loading weights of convolution #69
> loading weights of convolution #70
> no convolution #71
> loading weights of convolution #72
> loading weights of convolution #73
> no convolution #74
> loading weights of convolution #75
> loading weights of convolution #76
> loading weights of convolution #77
> loading weights of convolution #78
> loading weights of convolution #79
> loading weights of convolution #80
> loading weights of convolution #81
> no convolution #82
> no convolution #83
> loading weights of convolution #84
> no convolution #85
> no convolution #86
> loading weights of convolution #87
> loading weights of convolution #88
> loading weights of convolution #89
> loading weights of convolution #90
> loading weights of convolution #91
> loading weights of convolution #92
> loading weights of convolution #93
> no convolution #94
> no convolution #95
> loading weights of convolution #96
> no convolution #97
> no convolution #98
> loading weights of convolution #99
> loading weights of convolution #100
> loading weights of convolution #101
> loading weights of convolution #102
> loading weights of convolution #103
> loading weights of convolution #104
> loading weights of convolution #105
> Traceback (most recent call last):
> File "yolo3_one_file_to_detect_them_all.py", line 434, in
> _main_(args)
> File "yolo3_one_file_to_detect_them_all.py", line 409, in _main_
> image_h, image_w, _ = image.shape
> AttributeError: 'NoneType' object has no attribute 'shape'

Can someone please edit the first message of this issue to put the output in a code formatting?
This issue references all issues from 1 to 105 and that is confusing.
