### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by tarunchadha9** [experiencor/keras-yolo3#117]
I'm trying to run rbc detection on a specific file. Getting following error. Help. 

yolo3_one_file_to_detect_them_all.py:291: RuntimeWarning: invalid value encountered in greater
  netout[..., 5:] *= netout[..., 5:] > obj_thresh
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 434, in <module>
    _main_(args)
  File "yolo3_one_file_to_detect_them_all.py", line 421, in _main_
    correct_yolo_boxes(boxes, image_h, image_w, net_h, net_w)
  File "yolo3_one_file_to_detect_them_all.py", line 334, in correct_yolo_boxes
    boxes[i].xmin = int((boxes[i].xmin - x_offset) / x_scale * image_w)
ValueError: cannot convert float NaN to integer

**Comment by nfcopier** [comment]
I just got the same error. I'm pretty sure `x_scale` is `0` causing the division to result in NaN. But I'm not sure why `x_scale` ended up at `0`.

**Comment by nfcopier** [comment]
I got the same error. When I debugged this, every value in `netout` was `nan`. I'm not sure exactly why the prediction resulted in a bunch of `nan`. It seems, though, that the detect_them_all script is designed to work only with the pretrained weight mentioned in the repository's readme and with a default set of labels that work for the repository's datasets. My problem was that I was trying to run it with my own trained weights from my own dataset.

**Comment by guansheng020** [comment]
is it fixed? I got same issue

**Comment by tarunchadha9** [comment]
It works only with the pretrained weights mentioned in the file. Check output folder. Sometime it gives the output even with the error.

**Comment by guansheng020** [comment]
no any correct output on my test.  xmin, ymin, xmax, ymax are NaN on all boxes[i]

**Comment by Ranjeetrk** [comment]
any one find solution??

**Comment by cendelian** [comment]
do you fix it? could you share the solution?

**Comment by williamgun007** [comment]
that this issues already fixed ?

**Comment by tarunchadha9** [comment]
In my case despite error output was coming in the output folder. Check the output folder guys.

**Comment by mkarlan** [comment]
any updates?

**Comment by Xceptions** [comment]
2025, any updates?
