### ISSUE TITLE
error in loading pretrained weights

### ISSUE THREAD

**Issue by hemp110** [experiencor/keras-yolo3#13]
I trained a yolo3 model with backend.h5 for hours and get a new_weights.h5 (739MB), when I tried to continue training by loading new_weights.h5, there is error below, could someone kindly explain to me?

Loading pretrained weights.

Traceback (most recent call last):
  File "train.py", line 252, in <module>
    _main_(args)
  File "train.py", line 190, in _main_
    saved_weights_name  = config['train']['saved_weights_name']
  File "train.py", line 108, in create_model
    template_model.load_weights(saved_weights_name)
  File "/home/hemp/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/hemp/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 3354, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 147 layers.

**Comment by experiencor** [comment]
Sorry, you cannot stop the training halfway at the moment.
