### ISSUE TITLE
about train ：StopIteration: 'filename'

### ISSUE THREAD

**Issue by Wandering-Ghosts** [experiencor/keras-yolo3#130]
my own training data, anyone who can help me?
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "D:\object_detect\yolo3\generator.py", line 73, in __getitem__
    img, all_objs = self._aug_image(train_instance, net_h, net_w)
  File "D:\object_detect\yolo3\generator.py", line 159, in _aug_image
    image_name = instance['filename']
KeyError: 'filename'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 281, in <module>
    _main_(args)
  File "train.py", line 258, in _main_
    max_queue_size   = 8
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: 'filename'`

**Comment by paulbauriegel** [comment]
Looks like your config.json is incorrect or the VOC xml annotations do not contain the filename parameter
