### ISSUE TITLE
Training negative samples

### ISSUE THREAD

**Issue by TiongSun** [experiencor/keras-yolo3#135]
Hi, has anyone successfully train with negative samples? image with no object in it. What the annotation should be. I tried 0,0,0,0 but gen_anchor gives funny results:

average IOU for 9 anchors: nan
0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 71,87, 160,198

**Comment by paulbauriegel** [comment]
Can you provide a link to the dataset? From my point of view training with neg examples should work as well.

**Comment by TiongSun** [comment]
thank you for your reply. It is not an online database and I dont have a link. Do you know what format should it be for negative samples? 

It works fine but I would like to be sure what is the right format for negative sample? (leaving it blank or 0,0,0,0)?

**Comment by paulbauriegel** [comment]
Your are training on images in Pascal VOC annotation format. From my point of view a negative example would be an image without bounding box annotation:
```
<annotation type="list"><annotation>
	<folder>JPEGImages</folder>
	<filename>jpeg-file.jpg</filename>
	<path>/path/to/your/jpeg-file.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>640</width>
		<height>480</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
</annotation>
```

**Comment by david-hagar** [comment]
Also every YOLO tile that doesn't have a used anchor box is a kind of negative example, which is the vast majority of tiles. In fact there is a paper out there on "focus loss" that makes positive hit anchor boxes higher in loss to balance the hit/no-hit imbalance ( https://arxiv.org/abs/1708.02002 ).

**Comment by martinbel** [comment]
@david-hagar What you are saying is correct, but I think the "negative" images make sense if your model is predicting a set of classes in every image. This can happen if you train from scratch.

**Comment by paulbauriegel** [comment]
Yes trained some examples with only one class. Some of these images had no annotation. So these images are like negative examples. I haven't actively trained the network to not detect something, because YOLO is not designed for image classification. A wrong bounding box, however, should be punished by the mAP metric.

**Comment by AzZzOne** [comment]
> Hi, everyone!
> 
> Does anyone understand how to train with negative examples properly?
> 
> I have images with no objects and corresponding annotations in VOC format. I've only changed voc.py file so far: remove condition ` if len(img['object']) > 0:` in line 60.
> 
> What else should I change to make it work properly? Because now it looks like it do not learn from negative samples.

Ok, I figured out what the problem was: I forgot to rename filename tag in xml annotation for my augmented images... It seems to work now.

**Comment by cyrineee** [comment]
for multiclass with yolo , is images with another class object are considered negative samples ? or should i add negative samples ?

**Comment by andreasmarxer** [comment]
I'm also interested in training with negative samples. I'm working on a 1 class bounding box detection and wanted to improve training performance with negative, but kind of similar examples.

Therefore I did change the voc.py script around line 60 and add a train_mode boolean to the function parse_voc_annotation() which is per default False.

```
# train also on negative samples (w.o. labels)      added Andreas
          if train_mode is True:
                all_insts += [img]
            else:
                if len(img['object']) > 0:
                    all_insts += [img]
```

This should result to take all images for training but not for validation, when setting the boolean true only for getting train_ints, train_labels and NOT for valid_ints, valid_labels.

Of course this only works for manually splitted data, otherwise we have annotations without bounding boxes also in the validation set and this leads to an error for sure, due to the fact that the evaluation isn't made for annotations without any boxes.

But I still have errors in the evaluation after all epochs when only using data with bounding boxes for validation. Anyone has an idea why and can help me?

The erros are:

- `Epoch 00002: loss improved from 1035.09642 to 112.90983, saving model to window200_test.h5
dict_keys(['loss', 'yolo_layer_1_loss', 'yolo_layer_2_loss', 'yolo_layer_3_loss', 'lr'])
Traceback (most recent call last):
  File "train.py", line 312, in <module>
    _main_(args)
  File "train.py", line 295, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "/cluster/home/marxera/semester_project/utils/utils.py", line 48, in evaluate
    pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
  File "/cluster/home/marxera/semester_project/utils/utils.py", line 259, in get_yolo_boxes
    do_nms(boxes, nms_thresh)        
  File "/cluster/home/marxera/semester_project/utils/utils.py", line 166, in do_nms
    if bbox_iou(boxes[index_i], boxes[index_j]) >= nms_thresh:
  File "/cluster/home/marxera/semester_project/utils/bbox.py", line 57, in bbox_iou
    return float(intersect) / union
ZeroDivisionError: float division by zero`

- `Epoch 00040: loss did not improve from 7.50714
Epoch 00040: early stopping
dict_keys(['loss', 'yolo_layer_1_loss', 'yolo_layer_2_loss', 'yolo_layer_3_loss', 'lr'])
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    _main_(args)
  File "train.py", line 297, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "/cluster/home/marxera/semester_project/utils/utils.py", line 71, in evaluate
    all_annotations[i][label] = annotations[annotations[:, 4] == label, :4].copy()
IndexError: index 4 is out of bounds for axis 1 with size 0`


@paulbauriegel @AzZzOne @experiencor

**Comment by zmlim** [comment]
@andreasmarxer  Hi may i know if you managed to solve the issue with the IndexError: index 4 is out of bounds for axis 1 with size 0
