### ISSUE TITLE
while detect dog pic, occurs error. what's the version of python?

### ISSUE THREAD

**Issue by sixleaves** [experiencor/keras-yolo3#15]
Hi, while i run `python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg` command.i get those error message, can u help me?

```python
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 431, in <module>
    _main_(args)
  File "yolo3_one_file_to_detect_them_all.py", line 407, in _main_
    new_image = preprocess_input(image, net_h, net_w)
  File "yolo3_one_file_to_detect_them_all.py", line 270, in preprocess_input
    resized = cv2.resize(image[:,:,::-1]/255., (new_w, new_h))
TypeError: integer argument expected, got float
```

**Comment by sixleaves** [comment]
so bad, it's cannot support python3.6 and opencv3

**Comment by experiencor** [comment]
It's working with python2 in your case?
