### ISSUE TITLE
How to train from scratch with own data set? 

### ISSUE THREAD

**Issue by satish4github** [experiencor/keras-yolo3#194]

**Comment by satish4github** [comment]
Thank you for providing repo... 
@experiencor  could you give some suggestion about training from scratch with own data set ?

**Comment by zhiyilearn** [comment]
I have same question.

**Comment by kabrau** [comment]
I can help you, are many steps, you can read this link https://github.com/experiencor/keras-yolo2, it is the same with little differences. 
If you can't understand anyway, tell me and I will create a video for you.

**Comment by zhiyilearn** [comment]
If I use my own dataset to train YOLO v3, the step to label images. From the tutorial: 
 train annotations in VOC format
How to make train annotations in VOC format? What's exact VOC format.

**Comment by kabrau** [comment]
There are many options to annotate this
I made my tool: https://github.com/kabrau/PyImageRoi  (CreateBoundingBoxes)
But many people use: https://github.com/tzutalin/labelImg

**Comment by satish4github** [comment]
> I can help you, are many steps, you can read this link https://github.com/experiencor/keras-yolo2, it is the same with little differences.
> If you can't understand anyway, tell me and I will create a video for you.

Hi , I have 32x32 size images in my data set. I want to train yolo with whole(32x32 image itself) image... in my case whole image is the bounding box coordinates.... is it possible ? will it work?

**Comment by kabrau** [comment]
I don't know, what is the length of an object inside an image?
In your case, would not a classifier be better?

**Comment by satish4github** [comment]
Object size is same as image size(32x32) like cifar dataset
Classifier would say only object is there or not... But i need the object localization details also while predicting..

**Comment by kabrau** [comment]
@satish4github
I not sure, but I think that implementation does not work for you.
I'm curious, I don't understand If the object has the same size, why you need localization?

**Comment by zhiyilearn** [comment]
With raccoon data set I got errors, any idea? 

python train.py -c config.json

Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 170, in _main_
    config = json.loads(config_buffer.read())
  File "/opt/apps/Anaconda3/2019.03/envs/powerai16_ibm/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/apps/Anaconda3/2019.03/envs/powerai16_ibm/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/apps/Anaconda3/2019.03/envs/powerai16_ibm/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 49 (char 505)

**Comment by kabrau** [comment]
You need to debug this line to see the problem
File "/opt/apps/Anaconda3/2019.03/envs/powerai16_ibm/lib/python3.6/json/decoder.py", line 355

**Comment by satish4github** [comment]
I will check...

> I not sure, but I think that implementation does not work for you.

Basically i want train model with CIFAR image data set . I want to use the same model for predicting bounding boxes/object localization. 
1. In this case while training i don't need to need to do create bounding boxes while training data set.
2. Memory

**Comment by zhiyilearn** [comment]
Download link for backend weight not available: 

Download pretrained weights for backend at:
https://1drv.ms/u/s!ApLdDEW3ut5fgQXa7GzSlG-mdza6

**Comment by zhiyilearn** [comment]
Error message when I train raccoon dataset: 
python train.py -c config.json

OSError: Unable to open file (unable to open file: name = 'backend.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I think somehow I have to download backend weight somewhere. Is it initial weight for YOLO v3?

**Comment by zhiyilearn** [comment]
When I run training process for raccoon dataset as:
python train.py -c config.json
I got training error like this:
**************************************
Epoch 00027: loss did not improve from 5.13942
Epoch 00027: early stopping
/opt/apps/Anaconda3/2019.03/envs/powerai16_ibm/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/engine/saving.py:310: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
raccoon: 0.9681
mAP: 0.9681
***************************

Someone have any idea? My configuration is wrong?

**Comment by look4pritam** [comment]
You are getting 0.9681 mAP, which is good.

**Comment by zhiyilearn** [comment]
Training errors when use raccoon dataset:
It used to train process work. Any hint? 
python train.py -c config.json
***************************************
Using TensorFlow backend.
valid_annot_folder not exists. Spliting the trainining set.
Seen labels:    {}

Given labels:   ['raccoon']
Some labels have no annotations! Please revise the list of labels in the config.json.
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 182, in _main_
    config['model']['labels']
ValueError: not enough values to unpack (expected 4, got 3)
*******************************

config.json file looks like:
{
    "model" : {
        "min_input_size":       352,
        "max_input_size":       448,
        "anchors":              [10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326],
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "/home/zli04/2019SummerWork/raccoon_datast-master/images/",
        "train_annot_folder":   "/home/zli04/2019SummerWork/raccoon_dataset-master/annotations/",
        "cache_name":           "raccoon_train.pkl",

        "train_times":          3,
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epochs":            100,
        "warmup_epochs":        3,
        "ignore_thresh":        0.5,
        "gpus":                 "0,1",

        "grid_scales":          [1,1,1],
        "obj_scale":            5,
        "noobj_scale":          1,
        "xywh_scale":           1,
        "class_scale":          1,

        "tensorboard_dir":      "log_raccoon",
        "saved_weights_name":   "raccoon.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",
        "cache_name":           "",

        "valid_times":          1
    }
}

**Comment by zhiyilearn** [comment]
I try to train with my own dataset with YOLO version like:
***********************************
15 0.514000 0.254891 0.013600 0.029348
***********************************
In config.json file, should I need update/change anything? I noticed label option, should I change my label to 15 instead?

**Comment by zhiyilearn** [comment]
When I use annotation tools labelImg to annotate box for my own dataset, should I first change the images size to standard such as 288 x488 for raccoon? My own dataset image size is: 1250 x 920. I noticed Pascal/VOC format has image size information.

**Comment by look4pritam** [comment]
Keep image size and bounding boxes same as original image size. There is no
need to change image size to any standard size. Data augmentation tool will
take care of converting image size to standard size and so on.

**Comment by zhiyilearn** [comment]
How to set up min_input_size, max_input_size in config.json for your own dataset?

**Comment by zhiyilearn** [comment]
How to specify input_size in config.json  file? Assume my own image size is 1250 x 720.

**Comment by look4pritam** [comment]
There is no need to specify image size in config file. but you need to specify model size in the form of min and max model size.

**Comment by waelausy** [comment]
hello, what are the modifications that must be done ion the json file to support multiple classes custom training ?

**Comment by look4pritam** [comment]
Accuracy is less. How many input images are there?

**Comment by tejasmagia** [comment]
Around 125 images but still my objects are accurately detected.
