### ISSUE TITLE
json decoder error

### ISSUE THREAD

**Issue by Hashoma** [experiencor/keras-yolo3#206]
i followed the tutorial, but when i Generate anchors for data set, or start to train yolov3 this error is shown 
![Capture](https://user-images.githubusercontent.com/42260911/62103828-eac68880-b29d-11e9-8461-1de2ee9d442d.PNG)

json.decoder.JSONDecodeError: Invalid \escape: line 10 column 37 (char 306)

**Comment by IvanTheDiscombobulated** [comment]
Hi, @Hashoma, tell me please did you solve this problem? I've faced the same one when tried to launch training

**Comment by RCC-GIT** [comment]
Hello, I have the same problem  / No comments in my Jason file ...
When I test with Spider I have the folowing error 
from voc import parse_voc_annotation
Traceback (most recent call last):

  File "<ipython-input-4-39431e327040>", line 1, in <module>
    from voc import parse_voc_annotation

ModuleNotFoundError: No module named 'voc'

**Comment by RCC-GIT** [comment]
Hello, I did  : pip install voc   
which was not installed 
Now I have 
 from voc import parse_voc_annotation

ImportError: cannot import name 'parse_voc_annotation'

**Comment by IvanTheDiscombobulated** [comment]
@RCC-GIT I suppose it's an 'import functions from another file in the same directory' problem. I don't quite understand what you could have installed with 'pip install voc' command as it is just another .py file in the directory.
Try this "from .voc import parse_voc_annotation"
Good luck and have a nice day

**Comment by RCC-GIT** [comment]
I close and open the console in spider . from voc import parse_voc_annotation is ok now but I have another error now
File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
JSONDecodeError: Invalid \escape
I am working with windows 7 , is this have something do with UFT-8 encoding ?

**Comment by RCC-GIT** [comment]
For Windows7  anaconda + Phython  3.x
Path must be as \\  in Jason file (not \ and not  /)  and file path must be be asbsolute in All files . 
This has solved this problem for me .
