### ISSUE TITLE
Register with PyPI

### ISSUE THREAD

**Issue by monocongo** [experiencor/keras-yolo3#214]
My motivation for this issue is that I would like to use the code within an application I'm developing and would like to install this repository's code into my virtual environment via PyPI rather than from the GitHub repository. It seems that the project is solid/useful enough to warrant its inclusion on PyPI.

**Comment by monocongo** [comment]
BTW installation into a virtual environment may not even be possible since there's no `setup.py`, at least it doesn't work for me:
```
$ pip3 install git+git://github.com/experiencor/keras-yolo3.git
Collecting git+git://github.com/experiencor/keras-yolo3.git
  Cloning git://github.com/experiencor/keras-yolo3.git to /tmp/pip-req-build-4esq0zgf
  Running command git clone -q git://github.com/experiencor/keras-yolo3.git /tmp/pip-req-build-4esq0zgf
    ERROR: Command errored out with exit status 1:
     command: /home/james/miniconda3/envs/deep_monitor/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4esq0zgf/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4esq0zgf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-4esq0zgf/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/james/miniconda3/envs/deep_monitor/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-4esq0zgf/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
