### ISSUE TITLE
Resource Exhausted...

### ISSUE THREAD

**Issue by pkr97** [experiencor/keras-yolo3#222]
OS: Ubuntu 16.04
TF Version : 1.13.1
Python 3.5
==========================================

        "train_times":          3,
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epochs":            100,
        "warmup_epochs":        3,
        "ignore_thresh":        0.5,
        "gpus":                 "0,1",

        "grid_scales":          [1,1,1],
        "obj_scale":            5,
        "noobj_scale":          1,
        "xywh_scale":           1,
        "class_scale":          1,

===========================================

    train_model.fit_generator(
        generator        = train_generator, 
        steps_per_epoch  = len(train_generator) * config['train']['train_times'], 
        epochs           = config['train']['nb_epochs'] + config['train']['warmup_epochs'], 
        verbose          = 2 if config['train']['debug'] else 1,
        callbacks        = callbacks, 
        workers          = 4,
        max_queue_size   = 8
    )

===========================================

totalMemory: 3.95GiB freeMemory: 3.41GiB
2019-09-06 10:52:35.252845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-09-06 10:52:35.253593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-06 10:52:35.253612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-09-06 10:52:35.253620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-09-06 10:52:35.253748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3190 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)

.
.
.
2019-09-06 10:55:03.287913: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 2.61GiB
2019-09-06 10:55:03.287925: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: 
Limit:                  3345481728
InUse:                  2806625280
MaxInUse:               3160186368
NumAllocs:                    1986
MaxAllocSize:            872216064

2019-09-06 10:55:03.288000: W tensorflow/core/common_runtime/bfc_allocator.cc:271] **********************************___************************____*****************____************xx
2019-09-06 10:55:03.288027: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at transpose_op.cc:199 : Resource exhausted: OOM when allocating tensor with shape[8,32,417,417] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    _main_(args)
  File "train.py", line 258, in _main_
    max_queue_size   = 8
  File "/home/pkumars/TensorFlow/venv/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/pkumars/TensorFlow/venv/lib/python3.5/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/pkumars/TensorFlow/venv/lib/python3.5/site-packages/keras/engine/training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "/home/pkumars/TensorFlow/venv/lib/python3.5/site-packages/keras/engine/training.py", line 1449, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/pkumars/TensorFlow/venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2979, in __call__
    return self._call(inputs)
  File "/home/pkumars/TensorFlow/venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2937, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,417,417,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node replica_1/model_1/zero_padding2d_1/Pad}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node training/Adam/gradients/replica_0/model_1/bnorm_13/FusedBatchNorm_grad/FusedBatchNormGrad}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

==========================================================

I see that there is an error and that is related to resource.
" Resource exhausted: OOM when allocating tensor with shape[8,32,417,417] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
 "

How can I train with available resources?

I understand that process can be slow but it's possible to train for a single class of Raccoon dataset with available resources.

**Comment by andreasmarxer** [comment]
I do have kind of the same problem. Did you find a solution? @pkr97

**Comment by andreasmarxer** [comment]
I did solve this with a smaller batch size.
