### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3) 

### ISSUE THREAD

**Issue by J-Thunderbolt** [experiencor/keras-yolo3#227]
I use this command: ` python .\train.py -c .\config.json` but gives the following error. I did not change anything.

> Using TensorFlow backend.
> valid_annot_folder not exists. Spliting the trainining set.
> Seen labels:    {}
> 
> Given labels:   ['raccoon']
> Some labels have no annotations! Please revise the list of labels in the config.json.
> Traceback (most recent call last):
>   File ".\train.py", line 280, in <module>
>     _main_(args)
>   File ".\train.py", line 182, in _main_
>     config['model']['labels']
> ValueError: not enough values to unpack (expected 4, got 3)

**Comment by Aayaam-AI** [comment]
same problem

**Comment by ajayrawatsap** [comment]
I am able to successfully run using the same dataset
valid_annot_folder not exists. Splitting the training set.
Seen labels: 	{'raccoon': 217}

Given labels: 	['raccoon']

Training on: 	['raccoon']

You can run the code in a IDE like spyder adn debug to see what is causing issue

I  have created colab notebook which you can check. It runs fine only issue is I am getting memory error which is due to colab not allocating sufficient memory . It runs fine on Kaggle Kernal

https://colab.research.google.com/drive/1ZxKLmeN-EzB2QCaORX3pBr5AvPuJ-YVd#scrollTo=idsJ6njALsGr

**Comment by J-Thunderbolt** [comment]
> I am able to successfully run using the same dataset,see the output I am getting below
> 
> valid_annot_folder not exists. Splitting the training set.
> Seen labels: {'raccoon': 217}
> 
> Given labels: ['raccoon']
> 
> Training on: ['raccoon']
> 
> You can run the code in a IDE like spyder adn debug to see what is causing issue
> 
> I have created colab notebook which you can check. It runs fine only issue is I am getting memory error which is due to colab not allocating sufficient memory . It runs fine on Kaggle Kernal
> 
> https://colab.research.google.com/drive/1ZxKLmeN-EzB2QCaORX3pBr5AvPuJ-YVd#scrollTo=idsJ6njALsGr

thx bro it works on colab.

**Comment by smilexu1982** [comment]
delete your '.pkl' file

**Comment by husamkhateeb** [comment]
> I am able to successfully run using the same dataset,see the output I am getting below
> 
> valid_annot_folder not exists. Splitting the training set.
> Seen labels: {'raccoon': 217}
> 
> Given labels: ['raccoon']
> 
> Training on: ['raccoon']
> 
> You can run the code in a IDE like spyder adn debug to see what is causing issue
> 
> I have created colab notebook which you can check. It runs fine only issue is I am getting memory error which is due to colab not allocating sufficient memory . It runs fine on Kaggle Kernal
> 
> https://colab.research.google.com/drive/1ZxKLmeN-EzB2QCaORX3pBr5AvPuJ-YVd#scrollTo=idsJ6njALsGr

I am having the same problem but I can't understand your solution can you explain it please?

**Comment by animikhaich** [comment]
> > I am able to successfully run using the same dataset,see the output I am getting below
> > valid_annot_folder not exists. Splitting the training set.
> > Seen labels: {'raccoon': 217}
> > Given labels: ['raccoon']
> > Training on: ['raccoon']
> > You can run the code in a IDE like spyder adn debug to see what is causing issue
> > I have created colab notebook which you can check. It runs fine only issue is I am getting memory error which is due to colab not allocating sufficient memory . It runs fine on Kaggle Kernal
> > https://colab.research.google.com/drive/1ZxKLmeN-EzB2QCaORX3pBr5AvPuJ-YVd#scrollTo=idsJ6njALsGr
> 
> I am having the same problem but I can't understand your solution can you explain it please?

Please refer to this: https://github.com/experiencor/keras-yolo3/issues/243#issuecomment-583768111
