### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by Aayaam-AI** [experiencor/keras-yolo3#229]
error while using webcam with predict.py

> Traceback (most recent call last):
  File "predict.py", line 134, in <module>
    _main_(args)
  File "predict.py", line 49, in _main_
    batch_boxes = get_yolo_boxes(infer_model, images, net_h, net_w, config['model']['anchors'], obj_thresh, nms_thresh)
  File "C:\Users\aayaa\Desktop\Barrel Detection\yolov3\utils\utils.py", line 255, in get_yolo_boxes
    correct_yolo_boxes(boxes, image_h, image_w, net_h, net_w)
  File "C:\Users\aayaa\Desktop\Barrel Detection\yolov3\utils\utils.py", line 143, in correct_yolo_boxes
    boxes[i].xmin = int((boxes[i].xmin - x_offset) / x_scale * image_w)
OverflowError: cannot convert float infinity to integer

**Comment by SteveIb** [comment]
Hi, did you manage to solve it?
I'm getting the same error when i'm trying to train!

Epoch 00027: loss did not improve from 21.46444
Epoch 00027: early stopping
keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    _main_(args)
  File "train.py", line 272, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "/keras-yolo3-master/utils/utils.py", line 48, in evaluate
    pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
  File "/keras-yolo3-master/utils/utils.py", line 256, in get_yolo_boxes
    correct_yolo_boxes(boxes, image_h, image_w, net_h, net_w)
  File "/keras-yolo3-master/utils/utils.py", line 146, in correct_yolo_boxes
    boxes[i].ymin = int((boxes[i].ymin - y_offset) / y_scale * image_h)
OverflowError: cannot convert float infinity to integer

**Comment by Srinivasan95D** [comment]
> Hi, did you manage to solve it?
> I'm getting the same error when i'm trying to train!
> 
> Epoch 00027: loss did not improve from 21.46444
> Epoch 00027: early stopping
> keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was _not_ compiled. Compile it manually.
> warnings.warn('No training configuration found in save file: '
> Traceback (most recent call last):
> File "train.py", line 284, in
> _main_(args)
> File "train.py", line 272, in _main_
> average_precisions = evaluate(infer_model, valid_generator)
> File "/keras-yolo3-master/utils/utils.py", line 48, in evaluate
> pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
> File "/keras-yolo3-master/utils/utils.py", line 256, in get_yolo_boxes
> correct_yolo_boxes(boxes, image_h, image_w, net_h, net_w)
> File "/keras-yolo3-master/utils/utils.py", line 146, in correct_yolo_boxes
> boxes[i].ymin = int((boxes[i].ymin - y_offset) / y_scale * image_h)
> OverflowError: cannot convert float infinity to integer

I would say looking at the Training loss that your model hasn't learnt properly and bcoz of that, those weights are making values take a very large value >e+30 hence slowly moving to inf which throws this error.

**Comment by SteveIb** [comment]
@Srinivasan95D I removed early stopping. it is working better now. at least I have a model I can start trying it.

**Comment by KhalladiSofianeIT** [comment]
Hi i have this bug : 
How can i correct it ?

Skipping registering GPU devices...
2022-03-03 17:17:47.722828: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
2022-03-03 17:17:49.641743: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "evaluate.py", line 68, in <module>
    _main_(args)
  File "evaluate.py", line 56, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "C:\Users\GEnElect\Desktop\Khalladi_Sofiane_VehicleDetection\Notebook\utils\utils.py", line 50, in evaluate
    pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
  File "C:\Users\GEnElect\Desktop\Khalladi_Sofiane_VehicleDetection\Notebook\utils\utils.py", line 258, in get_yolo_boxes
    correct_yolo_boxes(boxes, image_h, image_w, net_h, net_w)
  File "C:\Users\GEnElect\Desktop\Khalladi_Sofiane_VehicleDetection\Notebook\utils\utils.py", line 146, in correct_yolo_boxes
    boxes[i].xmin = int((boxes[i].xmin - x_offset) / x_scale * image_w)
ValueError: cannot convert float NaN to integer
