### ISSUE TITLE
Error on tensorflow

### ISSUE THREAD

**Issue by babak-abad** [experiencor/keras-yolo3#231]
I try to train yolo3 but I get this error:
(win 10, no nvidia card, and my idea is pycharm 2019)

Using TensorFlow backend.
valid_annot_folder not exists. Spliting the trainining set.
Seen labels:    {'char': 41184}

Given labels:   ['char']

Training on:    ['char']

2019-10-25 16:31:33.640766: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in perfor
mance critical operations:  AVX
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2019-10-25 16:31:33.648295: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for b
est performance.
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    _main_(args)
  File "train.py", line 243, in _main_
    class_scale         = config['train']['class_scale'],
  File "train.py", line 132, in create_model
    class_scale         = class_scale
  File "C:\Users\Babak\PycharmProjects\keras-yolo3-master\keras-yolo3-master\yolo.py", line 232, in create_yolov3_model
    input_image = Input(shape=(None, None, 3)) # net_h, net_w, 3
  File "C:\Users\Babak\miniconda3\lib\site-packages\keras\engine\input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "C:\Users\Babak\miniconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Babak\miniconda3\lib\site-packages\keras\engine\input_layer.py", line 39, in __init__
    name = prefix + '_' + str(K.get_uid(prefix))
  File "C:\Users\Babak\miniconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

What is the problem? I'm new in python.

**Comment by shuuse** [comment]
Hi @babak-abad 
Please check your Tensorflow version. Maybe you are on 2.0 and have to downgrade to an older version. 
tensorflow==1.13.1 solved it for me.

**Comment by babak-abad** [comment]
Thank you. now it can be train.
