### ISSUE TITLE
Unable to generate anchors

### ISSUE THREAD

**Issue by ameanprogrammer** [experiencor/keras-yolo3#236]
Hi there, I'm getting the following error when trying to run gen_anchors.py
----
C:\Users\AMGCODE\Anaconda3\envs\tensorflow\pythonw.exe C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo3-master/gen_anchors.py -c config.json

Traceback (most recent call last):
  File "C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo3-master/gen_anchors.py", line 132, in <module>
    _main_(args)
  File "C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo3-master/gen_anchors.py", line 111, in _main_
    centroids = run_kmeans(annotation_dims, num_anchors)
  File "C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo3-master/gen_anchors.py", line 57, in run_kmeans
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo3-master/gen_anchors.py", line 57, in <listcomp>
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "C:\Users\AMGCODE\Anaconda3\envs\tensorflow\lib\random.py", line 195, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()

Process finished with exit code 1

----

I don't understand what the cause of this could be?  My config.json looks like the following: 

{
    "model" : {
        "min_input_size":       800,
        "max_input_size":       800,
        "anchors":              [55,69, 75,234, 133,240, 136,129, 142,363, 203,290, 228,184, 285,359, 341,260],
        "labels":               ["ship","vehicle","airplane"]
    },

    "train": {
        "train_image_folder":   "C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo-3-master/",
        "train_annot_folder":   "C:/Users/AMGCODE/Desktop/Python/ENEL645/Final_Project_ENEL645_AYK/keras-yolo-3-master/",
        "cache_name":           "sva_train.pkl",

        "train_times":          8,
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epochs":            100,
        "warmup_epochs":        3,
        "ignore_thresh":        0.5,
        "gpus":                 "0,1",

        "grid_scales":          [1,1,1],
        "obj_scale":            5,
        "noobj_scale":          1,
        "xywh_scale":           1,
        "class_scale":          1,

        "tensorboard_dir":      "logs",
        "saved_weights_name":   "svaweights.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",
        "cache_name":           "",

        "valid_times":          1
    }
}

--- 

The images I'm passing as an input are 800x800

**Comment by ak224001** [comment]
I got the same error please help!

**Comment by ak224001** [comment]
Hello @ameanprogrammer 
Everything is Good. Problem is here in <b>voc.py</b> file line number <b>44.</b>
<b>obj['name'] not in labels</b> always giving True.Your <b>labels</b> name is not matching with <b>obj['name']</b>
