### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3) 

### ISSUE THREAD

**Issue by husamkhateeb** [experiencor/keras-yolo3#243]
Using TensorFlow backend.
C:\Users\Home\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Home\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Home\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Home\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Home\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Home\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Seen labels:    {}

Given labels:   ['kangaroo']
Some labels have no annotations! Please revise the list of labels in the config.json.
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 182, in _main_
    config['model']['labels']
ValueError: not enough values to unpack (expected 4, got 3)
I keep having this error, is there anyway to solve it

**Comment by animikhaich** [comment]
Make sure that the dataset that you have given contains at least one of the labels that are defined in the `config.json` Line Number: 6.

For example, if your dataset contains the labels: `"Car", "Person" and "Bike"`, make sure you have mentioned either or all of the 3 labels in the `config.json` file. Do mind the upper and lower case of the labels. They have to match. 

Also, delete the existing **.pkl** file, (if any) before running the `train.py` script.
