### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by juz88** [experiencor/keras-yolo3#249]
The minimum size of the images in my dataset to train the network as it should be?
I have 100 images 24 x 24 pixels (obviously these are only for proof then I have a larger dataset but with many more images always of the same size) can they be fine or are larger images needed?

Epoch 00023: loss did not improve from 221.66633
Epoch 00023: early stopping
Traceback (most recent call last):
  File "train.py", line 289, in <module>
    _main_(args)
  File "train.py", line 277, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/utils.py", line 48, in evaluate
    pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/utils.py", line 260, in get_yolo_boxes
    do_nms(boxes, nms_thresh)        
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/utils.py", line 166, in do_nms
    if bbox_iou(boxes[index_i], boxes[index_j]) >= nms_thresh:
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/bbox.py", line 57, in bbox_iou
    return float(intersect) / union
ZeroDivisionError: float division by zero

**Comment by juz88** [comment]
{
    "model" : {
        "min_input_size":       240,
        "max_input_size":       480,
        "anchors":              [103,112, 135,131, 150,155, 171,136, 173,155, 173,175, 194,174, 195,155, 219,202],
        "labels":               ["sorgente"]
    },

    "train": {
        "train_image_folder":   "/Users/lucaalunni/Desktop/keras-yolo3/dataset/train/images/",
        "train_annot_folder":   "/Users/lucaalunni/Desktop/keras-yolo3/dataset/train/annots/",
        "cache_name":           "sorgente_train_new.pkl",
        
        "pretrained_weights":   "sorgente1.h5",

        "train_times":          3,
        "batch_size":           32,
        "learning_rate":        1e-4,
        "nb_epochs":            30,
        "warmup_epochs":        3,
        "ignore_thresh":        0.5,
        "gpus":                 "0,1",
        
        "grid_scales":          [1,1,1],
        "obj_scale":            5,
        "noobj_scale":          1,
        "xywh_scale":           1,
        "class_scale":          1,
        
        "tensorboard_dir":      "log_sorgente",
        "saved_weights_name":   "sorgente2.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "/Users/lucaalunni/Desktop/keras-yolo3/dataset/valid/images/",
        "valid_annot_folder":   "/Users/lucaalunni/Desktop/keras-yolo3/dataset/valid/annots/",
        "cache_name":           "sorgente_valid_new.pkl",

        "valid_times":          1
    }
}

**Comment by fjoanr** [comment]
size must be a multiple of 32, so 24x24 won't work
