### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by juz88** [experiencor/keras-yolo3#250]
I always have this error can someone tell me something about it?
and the loss is also very high, why?

Epoch 00033: loss did not improve from 250.62939
Epoch 00033: ReduceLROnPlateau reducing learning rate to 9.99999897748e-17.
/Users/lucaalunni/opt/anaconda3/envs/fermi/lib/python2.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

Traceback (most recent call last):
  File "train.py", line 291, in <module>
    _main_(args)
  File "train.py", line 279, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/utils.py", line 48, in evaluate
    pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/utils.py", line 260, in get_yolo_boxes
    do_nms(boxes, nms_thresh)        
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/utils.py", line 166, in do_nms
    if bbox_iou(boxes[index_i], boxes[index_j]) >= nms_thresh:
  File "/Users/lucaalunni/Desktop/keras-yolo3/utils/bbox.py", line 57, in bbox_iou
    return float(intersect) / union
ZeroDivisionError: float division by zero

**Comment by AhmedHessuin** [comment]
hello, i hope you fixed it.
in bbox.py :
inside def bbox_iou :
before the return float(intersected)/union
make it 

    if intersect==0:#if intersected ==0 is a special condition we made to solve issue in the code done by ahmed hessuin
        return 0#retun 0
    return float(intersect) / union # return the intersected area over the union area

**Comment by 459below** [comment]
Yes, I had the same error and I came up with the exact same solution 👍

So I thought about what might happen here. Since this error does not always occur but just with a certain set of weights after training, I am assuming that the prediction in these cases is not a rectangle, but a line. I.e. with a length of 0 in one of the dimensions. What follows from this assumption is, that the area of both the intersection and the union has to be 0 as well. And since this a very bad prediction it would be most appropriate to return an IoU of 0.

I printed out intersect and union for the error case and in my instance intersect and union turned out to be 0 at the same time. Hence I think it would make sense to do this check right affter calculating the intersect like:

```
intersect = intersect_w * intersect_h
if intersect==0
    return 0
```

Since we just divide the intersect and 0 divided by any real number is 0. except for the case of 0 divided by 0.
