### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3) when starting the training.

### ISSUE THREAD

**Issue by ghost** [experiencor/keras-yolo3#255]
To produce error using the racoon dataset:
python3 train.py -c config.json

Seen labels: 	{}

Given labels: 	['raccoon']
Some labels have no annotations! Please revise the list of labels in the config.json.
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    _main_(args)
  File "train.py", line 192, in _main_
    config['model']['labels']
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by ghost** [comment]
Solved by not using the racoon dataset and using my own
