### ISSUE TITLE
ValueError: Shapes (1, 1, 1024, 63) and (255, 1024, 1, 1) are incompatible

### ISSUE THREAD

**Issue by ghost** [experiencor/keras-yolo3#256]
Loading pretrained weights. model.h5

Traceback (most recent call last):
  File "/Users/emadboctor/Desktop/keras-yolo3/train.py", line 289, in <module>
    _main_(args)
  File "/Users/emadboctor/Desktop/keras-yolo3/train.py", line 251, in _main_
    class_scale         = config['train']['class_scale'],
  File "/Users/emadboctor/Desktop/keras-yolo3/train.py", line 161, in create_model
    template_model.load_weights(saved_weights_name)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 1237, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3323, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 819, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1110, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 1, 1024, 63) and (255, 1024, 1, 1) are incompatible

**Comment by zmlim** [comment]
@emadboctorx  hi did you manage to solve this issue?

**Comment by ghost** [comment]
Yeah, I managed to solve the issue by downgrading tensorflow to 1.15
