### ISSUE TITLE
Augmented images (and xml files) not used

### ISSUE THREAD

**Issue by NoxTheXelor** [experiencor/keras-yolo3#275]
I made a data augmentation of my dataset and then move the images into the trains folders
But when I run the trainn script, it warn me the number of detected labels, wich are the same of those before the data augmentation. 
In another words, the augmented images and xml file are not took into account 
![image](https://user-images.githubusercontent.com/26748640/83150883-1d2e5580-a0fc-11ea-87ac-446cadbcb9dc.png)
Edit : I have remove the vanilla dataset (I just let the the augmented images & labels) from the trains folders and I got this : 
```
valid_annot_folder not exists. Spliting the trainining set.
Seen labels:    {'Background': 26, 'Spallation': 1313, 'ExposedBars': 1047, 'CorrosionStain': 1174, 'Efflorescence': 694, 'Crack': 1819}

Given labels:   ['Crack', 'Spallation', 'Efflorescence', 'ExposedBars', 'CorrosionStain']

Training on:    ['CorrosionStain', 'Crack', 'Efflorescence', 'ExposedBars', 'Spallation']

WARNING:tensorflow:From C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From e:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\yolo.py:151: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\callbacks\callbacks.py:998: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
WARNING:tensorflow:From C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\backend\tensorflow_backend.py:431: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\backend\tensorflow_backend.py:438: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\callbacks\tensorboard_v1.py:200: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\callbacks\tensorboard_v1.py:203: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0001151.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0000700.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0000052.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0000752.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0000776.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0000328.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0001143.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0001094.jpg
Cannot find  E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\train_image_folder\image_0001182.jpg
Epoch 1/103
Traceback (most recent call last):
  File "e:/EPHEC/Bac_3/Q2/TFE/experiencor/keras-yolo3-master/train.py", line 296, in <module>
    _main_(args)
  File "e:/EPHEC/Bac_3/Q2/TFE/experiencor/keras-yolo3-master/train.py", line 272, in _main_
    max_queue_size   = 8
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\engine\training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\utils\data_utils.py", line 625, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\utils\data_utils.py", line 610, in get
    inputs = future.get(timeout=30)
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Antoine\Anaconda3\envs\experiencor\lib\site-packages\keras\utils\data_utils.py", line 406, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "e:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\generator.py", line 73, in __getitem__
    img, all_objs = self._aug_image(train_instance, net_h, net_w)
  File "e:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master\generator.py", line 163, in _aug_image
    image = image[:,:,::-1] # RGB image
TypeError: 'NoneType' object is not subscriptable
PS E:\EPHEC\Bac_3\Q2\TFE\experiencor\keras-yolo3-master>
```
Does someone have an idea why ?
Thanks

**Comment by NoxTheXelor** [comment]
Ok, I didn't update the pkl file ...
 It took me days to figure it out ... XD
