### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by shekarneo** [experiencor/keras-yolo3#281]
i got this error but i have labels: ['dog'] in config file
```
Seen labels: 	{}

Given labels: 	['dog']
Some labels have no annotations! Please revise the list of labels in the config.json.
Traceback (most recent call last):
  File "train.py", line 289, in <module>
    _main_(args)
  File "train.py", line 191, in _main_
    config['model']['labels']
ValueError: not enough values to unpack (expected 4, got 3)
```

**Comment by shekarneo** [comment]
was caused by cache file
