### ISSUE TITLE
question about backend

### ISSUE THREAD

**Issue by houxy12** [experiencor/keras-yolo3#41]
Thank you very much for your contribution!
I download your code from github, and test on my computer.
When I run "python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg",the problem occured:
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 70, in _main_
    anchors             = config['model']['anchors'])
    x = LeakyReLU(alpha=0.1)(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 454, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/advanced_activations.py", line 46, in call
    return K.relu(inputs, alpha=self.alpha)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2933, in relu
    x = tf.nn.leaky_relu(x, alpha)
AttributeError: 'module' object has no attribute 'leaky_relu'

I don't know why. I also run yolo2 on my computer, and I can train on my own dataset, but after this error occured, yolo2 can't run,too. And has the same problem. Do you have any idea?

**Comment by houxy12** [comment]
I change keras from 2.1.6 to 2.1.2 and solve the problem.

**Comment by SunHeng-BUPT** [comment]
change you TF edition to 1.4.0   CUDA8    cuDNN6

**Comment by SunHeng-BUPT** [comment]
Change your TF edition to 1.4.0 (CUDA8 cuDNN6).TF 1.2.0 has no attribute 'leaky_relu'.
