### ISSUE TITLE
StopIteration: 'filename'

### ISSUE THREAD

**Issue by thomasdf** [experiencor/keras-yolo3#63]
I'm trying to train on my own dataset, but I get the following error. Any ideas?

```
Epoch 1/103
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 257, in _main_
    max_queue_size   = 8
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
StopIteration: 'filename'
```

**Comment by experiencor** [comment]
Seems like some xml annotation file lacks the filename field. Do ```print``` to debug.
