### ISSUE TITLE
What value to set to min_input_size and max_input_size in config.json?

### ISSUE THREAD

**Issue by ManjeeraJagiri** [experiencor/keras-yolo3#66]
Can someone please explain what do 'min_input_size' and 'max_input_size' in config.json mean? Are they related to yolo backend architecture? 

Thanks

**Comment by experiencor** [comment]
@ManjeeraJagiri They define the range to vary the size of the image during training. Should be a multiple of 32.

**Comment by ManjeeraJagiri** [comment]
@experiencor , Thanks a lot! Can you please help with two more things?
1) Is there a weights file for PASCAL VOC? If yes, where is it in the folder?
2) I am getting the same sort of error for most of the images when I run the command `python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i path/to/file//raccoon-1.jpg`. Any idea why?

```
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 459, in <module>
    _main_(args)
  File "yolo3_one_file_to_detect_them_all.py", line 418, in _main_
    new_image = preprocess_input(image, net_h, net_w)
  File "yolo3_one_file_to_detect_them_all.py", line 276, in preprocess_input
    new_image[int((net_h-new_h)//2):int((net_h+new_h)//2), int((net_w-new_w)//2):int((net_w+new_w)//2), :] = resized
ValueError: could not broadcast input array from shape (266,416,3) into shape (267,416,3)
```

**Comment by AmIr-KinG** [comment]
@experiencor Thank you, your code is almost perfect! :)
but I have encountered with this problem too, only for some images.
I tried to detect some pictures of the kangaroo dataset,
but some of the images like "00001.jpg", "00004.jpg" or "00014.jpg"!
I tried to detect the images using both "yolov3.weights" and a trained model of your code with the kangaroo dataset.
The error showed up anyway.
I hope the information I gave helps to solve the problem.

**Comment by ManjeeraJagiri** [comment]
@AmIr-KinG, I think the issue is with the dimensions of the images, and not with the weights. Were you able to solve it?
Also, I am getting the following error whenever I try to load any of the weights in the zoo folder 
`OSError: Unable to open file (File signature not found)` . Did you ever get it?

Thanks

**Comment by ManjeeraJagiri** [comment]
@AmIr-KinG , I ran the following images you had given in the preprocessing code snippet. Seems to work fine.
```
import cv2
import numpy as np

image_path='path/to/file/00014.jpg'
image = cv2.imread(image_path)
net_h,net_w=416,416
new_h, new_w, _ = image.shape

# determine the new size of the image
if (float(net_w)/new_w) < (float(net_h)/new_h):
    new_h = (new_h * net_w)//new_w
    new_w = net_w
else:
    new_w = (new_w * net_h)//new_h
    new_h = net_h
    
# resize the image to the new size
resized = cv2.resize(image[:,:,::-1]/255., (new_w, new_h))

# embed the image into the standard letter box
new_image = np.ones((net_h, net_w, 3)) * 0.5
new_image[(net_h-new_h)//2:(net_h+new_h)//2, (net_w-new_w)//2:(net_w+new_w)//2, :] = resized
new_image = np.expand_dims(new_image, 0)
```

**Comment by AmIr-KinG** [comment]
@ManjeeraJagiri I think there is something wrong with the weight files because they all have size of 134 bytes!
The weights I got from training have a size of approximately 247 MB!!

Have you try checking the images I mentioned with "detect.py" or "yolo3_one_file_to_detect_them_all.py"?
Or just the preprocessing code snippet? I also got no error from this part.

**Comment by ManjeeraJagiri** [comment]
@AmIr-KinG , I checked the images with only the preprocessing code snippet in detect.py since I was facing an issue with the one in yolo3_one_file_to_detect_them_all.py. There is a difference in the preprocessing code part in these two files.
