### ISSUE TITLE
Getting Unknown Layer : YoloLayer on predict.py

### ISSUE THREAD

**Issue by ankitshekhawat** [experiencor/keras-yolo3#9]
When I try to do prediction I am getting this error:

```
Traceback (most recent call last):
  File "predict.py", line 151, in <module>
    _main_(args)
  File "predict.py", line 34, in _main_
    infer_model = load_model(config['train']['saved_weights_name'])
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\engine\topology.py", line 2514, in from_config
    process_layer(layer_data)
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\engine\topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\engine\topology.py", line 2514, in from_config
    process_layer(layer_data)
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\engine\topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\ankit\AppData\Roaming\Python\Python36\site-packages\keras\utils\generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: YoloLayer

```

I tried adding YoloLayer to custom objects as well but then I get:
`TypeError: __init__() missing 5 required positional arguments: 'anchors', 'max_grid', 'batch_size', 'warmup_batches', and 'ignore_thresh'`

Any clues?

**Comment by experiencor** [comment]
@ankitshekhawat Did you stop the training half way? During training, the code saves the multi-GPU model. Loading that model will give you this error. You should start train.py again but disable fit_generator to allow the code to go straightly to loading the multi-GPU model and save the single-GPU model.

**Comment by creotiv** [comment]
That's because you saved only train_model and not inference_model.
Just add try/except over train_model.fit_generator() and on interrupt it will save also inference_model. But i recommend also change names of train/inference model files, so it not rewrited by other.

**Comment by ninjakx** [comment]
Reduce the size of max_q_size. 
I had the same problem resolved it by reducing it.

[https://github.com/keras-team/keras/issues/3675](#3675)

**Comment by creotiv** [comment]
Print out exception from fit_generator . This is exception is after fit_generator.
Also don't interrupt training on validation phase cause it writing model at that time, so you can broke it.
Normal size of the inference model is about 200M and for train 750M, if it not so, then delete it and retrain.
